language: php
php:
  - 5.3
before_script:
  - git clone git://github.com/marmotz/sia.git
  - git clone git://github.com/marmotz/LinksChecker.git
  - composer install -d sia
  - mkdir -p output/fr output/en
  - ./sia/bin/sia -i fr -o output/fr -t atoum
  - ./sia/bin/sia -i en -o output/en -t atoum
  - export ADDITIONAL_PATH=`php -i | grep -F --color=never 'Scan this dir for additional .ini files'`
  - cat ${ADDITIONAL_PATH:42}/xdebug.ini
  - sed '/xdebug.max_nesting_level/d' ${ADDITIONAL_PATH:42}/xdebug.ini > xdebug.ini
  - echo 'xdebug.max_nesting_level=9999' | tee xdebug.ini
  - sudo mv xdebug.ini ${ADDITIONAL_PATH:42}/xdebug.ini
  - cat ${ADDITIONAL_PATH:42}/xdebug.ini
script: ./LinksChecker/check output/fr/chapter1.html && ./LinksChecker/check output/en/chapter1.html
#notifications:
#  irc: "irc.freenode.org##atoum"